/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as FlowsNewRouteImport } from './routes/flows.new'
import { Route as FlowsFlowIdIndexRouteImport } from './routes/flows.$flowId.index'
import { Route as FlowsFlowIdEditRouteImport } from './routes/flows.$flowId.edit'
import { Route as FlowsFlowIdRunRouteImport } from './routes/flows.$flowId.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsNewRoute = FlowsNewRouteImport.update({
  id: '/flows/new',
  path: '/flows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdIndexRoute = FlowsFlowIdIndexRouteImport.update({
  id: '/flows/$flowId/',
  path: '/flows/$flowId/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdEditRoute = FlowsFlowIdEditRouteImport.update({
  id: '/flows/$flowId/edit',
  path: '/flows/$flowId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRunRoute = FlowsFlowIdRunRouteImport.update({
  id: '/flows/$flowId/run',
  path: '/flows/$flowId/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/flows/new': typeof FlowsNewRoute
  '/flows/$flowId/edit': typeof FlowsFlowIdEditRoute
  '/flows/$flowId/run': typeof FlowsFlowIdRunRoute
  '/flows/$flowId/': typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/flows/new': typeof FlowsNewRoute
  '/flows/$flowId/edit': typeof FlowsFlowIdEditRoute
  '/flows/$flowId/run': typeof FlowsFlowIdRunRoute
  '/flows/$flowId': typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/flows/new': typeof FlowsNewRoute
  '/flows/$flowId/edit': typeof FlowsFlowIdEditRoute
  '/flows/$flowId/run': typeof FlowsFlowIdRunRoute
  '/flows/$flowId/': typeof FlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/stats'
    | '/flows/new'
    | '/flows/$flowId/edit'
    | '/flows/$flowId/run'
    | '/flows/$flowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/stats'
    | '/flows/new'
    | '/flows/$flowId/edit'
    | '/flows/$flowId/run'
    | '/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/stats'
    | '/flows/new'
    | '/flows/$flowId/edit'
    | '/flows/$flowId/run'
    | '/flows/$flowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  FlowsNewRoute: typeof FlowsNewRoute
  FlowsFlowIdEditRoute: typeof FlowsFlowIdEditRoute
  FlowsFlowIdRunRoute: typeof FlowsFlowIdRunRoute
  FlowsFlowIdIndexRoute: typeof FlowsFlowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/new': {
      id: '/flows/new'
      path: '/flows/new'
      fullPath: '/flows/new'
      preLoaderRoute: typeof FlowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/': {
      id: '/flows/$flowId/'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId/'
      preLoaderRoute: typeof FlowsFlowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/edit': {
      id: '/flows/$flowId/edit'
      path: '/flows/$flowId/edit'
      fullPath: '/flows/$flowId/edit'
      preLoaderRoute: typeof FlowsFlowIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/run': {
      id: '/flows/$flowId/run'
      path: '/flows/$flowId/run'
      fullPath: '/flows/$flowId/run'
      preLoaderRoute: typeof FlowsFlowIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  FlowsNewRoute: FlowsNewRoute,
  FlowsFlowIdEditRoute: FlowsFlowIdEditRoute,
  FlowsFlowIdRunRoute: FlowsFlowIdRunRoute,
  FlowsFlowIdIndexRoute: FlowsFlowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
